apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  namespace: default
spec:
  replicas: 2

  selector:
    matchLabels:
      app: devops-app
  
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
        - name: app
          image: workshop/app:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: devops-app
spec:
  selector:
    app: devops-app
  
  ports:
    - port: 80
      targetPort: 8080
